FROM almalinux:9
# CMD ["ping", "google.com"]
# ENTRYPOINT ["ping", "google.com"]
# CMD can be replaced at container runtime
# ENTRYPOINT cannot be replaced at container run time
CMD ["google.com"] 
ENTRYPOINT ["ping"]